[package]
name = "kk"
version = "0.1.0"
authors = ["Wong Jia Hau <hou32hou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
